### ISSUE TITLE
Add Contribute Command

### ISSUE THREAD

**Issue by XordK** [XordK/OneBot#20]
Create a discord embed object

Set the title to "Contributing to OneBot"

Set the description to "If you want to help the further development of the bot, please get in touch or visit the github repository"

add the repository url to the embed and in the embed description on a new line

**Comment by XordK** [comment]
added as `/contrib learn`

WIP

**Comment by FalkoKotva** [comment]
Hello, can I work on this problem? I was a little too busy. And I have a problem starting this project due to problems with the database.

**Comment by XordK** [comment]
Hi @FalkoKotva,
Of course you can, all contributions are welcome! I will update the specification for this issue in the above description as I have forgotten to do so earlier. Please take your time and let me know of any issues I can help you with.

**Comment by FalkoKotva** [comment]
Thanks, I'm currently having trouble getting the database up and running. according to the code, you first try to connect to the database and only then create it according to build.sql. So I think there should be some check on the db or create a separate module to create the db.

**Comment by XordK** [comment]
The sqlite3 package will automatically create a database if one is not detected at the specified path when calling

    sqlite3.connect(PATH_TO_DATABASE)

So it should be automatically created in `data/db/db.sqlite3` when the code is ran for the first time.
Let me know if I can help with anything else :slightly_smiling_face:

**Comment by FalkoKotva** [comment]
Hello, is this how it should look like? The message is a link to github. and you can set a thumbnail later.
![image](https://user-images.githubusercontent.com/79063139/201718012-87ee7cee-b7f2-4be9-9003-699454eae951.png)

**Comment by XordK** [comment]
Hi FalkoKotva, yes this looks fantastic!

You can make a merge request from this link: https://github.com/XordK/OneBot/compare
_(please merge into jones-dev branch)_

Once I've looked over the changes I'll merge them into main :smile:

**Comment by FalkoKotva** [comment]
Hi, i created merge request.
 I hope I did it right and you will be satisfied with the result. :)

**Comment by XordK** [comment]
The result is great! I've merged the changes and they're now on the main branch.
