### ISSUE TITLE
Add reaction to birthday celebration

### ISSUE THREAD

**Issue by XordK** [XordK/OneBot#47]
Make the bot react with an appropriate emoji to the birthday celebration embed message. Do this so users can say happy birthday without sending a message by reacting with the same emoji.

If a custom emoji is use, make sure to have a default emoji as a fallback in case the custom one gets deleted.

Also add a footer to the birthday embed that says something like "React with :emoji: to wish happy birthday!"

**Comment by XordK** [comment]
Hi @FalkoKotva!

Please feel free to make a fork of the repository if you would like to contribute!
Once changes are finalized on your fork, open a pull request and I'll review the changes for a merge.

I do just want to ask if you are a member of the Derby College Group discord server? No worries if not, you are still free to reuse this repository in your own discord bot if you wish.

Unfortunately I cannot guarantee that the bot will work in your environment or on your own server without some minor tweaks due to the way I have developed it. For one, you will have to replace the id's at `data/test.config.json` with existing channel id's from your discord server. For two, it's to my understanding that the dependencies file `requirements.txt` is broken, so you may find yourself having to install some extra packages after setting up your development environment.

If you need any help with anything regarding this issue then please drop another comment in this thread, good luck!

**Comment by FalkoKotva** [comment]
Hi, i am not a member. I will try to set up this project in my development enviroment and try to test it and let you know if I have any problems or questions and thanks.

**Comment by XordK** [comment]
Deadline reached, worked on and added in latest commit.
